version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: stmMysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rashu@2559
      MYSQL_DATABASE: stm
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pRashu@2559" ]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build: .
    container_name: stmSpringBoot
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rashu@2559
volumes:
  mysql_data:
